
POST http://localhost:3000/login  HTTP/1.1
content-type: application/json

{
    "mail":"ja.sabando@duocuc.cl",
    "password":"4523452345"
}
###

POST http://localhost:3000/signup  HTTP/1.1
content-type: application/json

{
    "mail":"ja.sabando@duocuc.cl",
    "password":"4523452345",
    "name":"javier",
    "lastName":"sabando"
}

###
GET  http://localhost:3000/user  HTTP/1.1
content-type: application/json

{
    "mail":"ja.sabando@duocuc.cl",
    "password":"12345678",
    "name":"javier",
    "lastName":"sabando"
}

###
GET http://localhost:3000/user?id=64ee65824cd8b4ff6329ba16 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWU0ZGQzMDg5YzM0ZTlhNzFkNmRmMCIsIm1haWwiOiJqYXZpZXIyMDAwYXNyQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiNjRlZTRkY2YwODljMzRlOWE3MWQ2ZGQ5IiwiaWF0IjoxNjkzMzQ4ODg2LCJleHAiOjE2OTU5NDA4ODZ9.vlXbIFHbhTR6B9LzEyfBA9U6eY4Kwl7hF1Omx3jK5tg

